use epsilon_bot;

Insert into Suggestion_Queries (BotCode , SubCode , Question , Question_type , Question_frequency) values
('LOGOV001' , 'GC' , 'Which project has the high  difference between Budgeted and Actual Transportation Costs?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'What percentage of trips were delayed in the IOCL-DHDT Project?' , 'Dynamic' , '0'),
('LOGOV001' , 'GC' , 'Which trip had the longest delay, and which project did it belong to?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'What percentage of shipments were delayed by more than 5 days?' , 'Dynamic' , '0'),
('LOGOV001' , 'GC' , 'Which project had the longest average delay in delivery?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'What was the transportation cost for shipment from Anjar to RHCU?' , 'Dynamic' , '0'),
('LOGOV001' , 'GC' , 'Which shipment had the highest cost due to extra length/width/height charges?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'How many trips had fuel escalation charges ?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'Draw a horizontal bar chart representing the 5 trips with the highest transportation costs.' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'create a bar chart on the average delay caused by each LSP' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'create a clustered bat chart on comparison between budgeted transportation cost and actual transportation cost for each LSP?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'How often is there a delay from the vadodara to the DHDT project site arrival?' , 'Dynamic' , '0'),
('LOGOV001' , 'GC' , 'Give me how many no of trips are above budget and how many are below budget ?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'How many trips are above budget and how many are below budget for each project?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'What was the most common reason for the above budget trips in project IOCL-DHDT?' , 'Dynamic' , '0'),
('LOGOV001' , 'GC' , 'From Vadodara to DHDT Project Site what is the transportation cost and transit time ?' , 'Dynamic' , '0'),
('LOGOV001' , 'GC' , 'Create  the trips by LSP in a stacked bar chart, indicating which LSP has the least trips.' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'How much was charged for the wait time at the loading point and unloading point for IOCL-DHDT ?' , 'Dynamic' , '0'),
('LOGOV001' , 'GC' , 'How much longer did the delivery take compared to the original plan?' , 'Static' , '0'),
('LOGOV001' , 'GC' , 'How often is there a delay from the vadodara to the DHDT project site arrival?' , 'Dynamic' , '0');




Create table Suggestion_Queries(
BotCode varchar(50),
SubCode varchar(50),
Question_Id INT PRIMARY KEY auto_increment,
Question varchar(500) not null,
Question_type varchar(20) not null,
Question_frequency INT,

Foreign key (BotCode) references bots(BotCode) on delete set null
);

Insert into Suggestion_Queries (BotCode , SubCode , Question , Question_type , Question_frequency) values
('LOGOV001','ODC','Which component got maximum delay in IOCL Barauni project ?','Dynamic','0'),
('LOGOV001','ODC','How many trips got delayed in HRRL DFCCU Project?','Dynamic','0'), 
('LOGOV001','ODC','Provide me the  average transportation cost charged by LSPs in moving a component from Pune to Paradip ?','Dynamic','0'),
('LOGOV001','ODC','Give me the list of LSP who will transport a component from Hazira to Paradip.','Dynamic','0'),
('LOGOV001','ODC','Provide the per km rate for the LSPs who are picking up from Vadodara.','Dynamic','0'),
('LOGOV001','ODC','List down the LSP which are delivering to Barauni.','Dynamic','0'),
('LOGOV001','ODC','Create the chart for LSP wise transportation cost across all the projects.','Static','0'),
('LOGOV001','ODC','Give me project wise transportation cost in the provided document.','Static','0'),
('LOGOV001','ODC','How many trips were over budget for HPCL RUF Project','Dynamic','0'),
('LOGOV001','ODC','Create a clustered bar chart for LSP wise total no of trips and over budget trips','Static','0'),
('LOGOV001','ODC','What was the transportation cost for the largest component that got transported in HURL Sindri ?','Dynamic','0'),
('LOGOV001','ODC','Which was the largest component that got transported overall the document ?','Static','0'),
('LOGOV001','ODC','What was the most common reason for the above budget trips in project IOCL Paradip?','Dynamic','0'),
('LOGOV001','ODC','From Vadodara to Barauni, which LSP can do in less time ?','Dynamic','0'),
('LOGOV001','ODC','From Hazira to Barmer, which LSP can do in less transportation cost  ?','Dynamic','0'),
('LOGOV001','ODC','What was the most common reason for the delayed trips in HRRL DFCCU project ?','Dynamic','0'),
('LOGOV001','ODC','Give the list of suppliers for pickup location Hazira.','Dynamic','0'),
('LOGOV001','ODC','Provide the analysis of rate per km by vehicle in the given document.','Static','0'),
('LOGOV001','ODC','For compressor, for a range of weight 10 -20 MT , which lsp is the best ?','Dynamic','0'),
('LOGOV001','ODC','For delivery location Pachpadra, considering the time, which vehicle is the best to use ?','Dynamic','0'),
('LOGOV001','ODC','Provide the details of items dispatched to Barmer, if any .','Dynamic','0'),
('LOGOV001','ODC','I have a shipment that needs to ship within the distance of range 50-100 kms, so which lsp is charging less cost per km ?','Dynamic','0'),
('LOGOV001','ODC','Provide the per MT rate for the LSPs who are picking up from Hazira.','Dynamic','0');

select * from Suggestion_Queries;
Insert into Suggestion_Queries (BotCode , SubCode , Question , Question_type , Question_frequency) values
('LOGOV001','Imports','Provide me the LSP details of the trips with maximum and minimum delay.','Static','0'),
('LOGOV001','Imports','How many trips got delayed in the provided document ?','Static','0'),
('LOGOV001','Imports','List down the average transportation costs of LSPs having pickup location Ahmedabad.','Dynamic','0'),
('LOGOV001','Imports','List down the LSP which are delivering shipment to Chennai.','Dynamic','0'),
('LOGOV001','Imports','Create a clustered bar chart for LSP wise total no of trips and over budget trips.','Static','0'),
('LOGOV001','Imports','From Ahmedabad to Jeddah, which LSP can do it in less cost ?','Dynamic','0'),
('LOGOV001','Imports','Provide me the count of incoterms in the form of pie chart.','Static','0'),
('LOGOV001','Imports','Give me a distribution chart for transportation mode project wise using a clustered chart.','Static','0'),
('LOGOV001','Imports','Which trip got maximum over budgeted ?','Static','0'),
('LOGOV001','Imports','Who is corresponding supplier to that trip which was maximum under budget ?','Static','0'),
('LOGOV001','Imports','For the given document, analyse the project wise cost in tabular form.','Static','0'),
('LOGOV001','Imports','List the items transported through sea in Farabi project.','Dynamic','0'),
('LOGOV001','Imports','From Katupalli to Jeddah, which is the most feasible mode of transportation ?','Dynamic','0'),
('LOGOV001','Imports','If the item has to be imported to China, considering the cost , which incoterm is best ?','Dynamic','0'),
('LOGOV001','Imports','Give the details of the trip which got most delayed in Farabi project.','Dynamic','0'),
('LOGOV001','Imports','I want to dispatch my shipment to USA, provide me the list of suppliers.','Dynamic','0');

Insert into Suggestion_Queries (BotCode , SubCode , Question , Question_type , Question_frequency) values
('LOGOV001','Multimode','From Hazira to Barmer, what is the difference between the actual and budgeted cost?','Dynamic','0'),
('LOGOV001','Multimode','Are there specific suppliers consistently associated with higher transportation costs?','Static','0'),
('LOGOV001','Multimode','What is the total volume of cargo shipped for  project Barauni/Sindri ?','Dynamic','0'),
('LOGOV001','Multimode','Which shipment went over budget the most?','Static','0'),
('LOGOV001','Multimode','Which logistics service providers are consistently meeting delivery timelines?','Static','0'),
('LOGOV001','Multimode','How many shipments have exceeded their transit time?','Static','0'),
('LOGOV001','Multimode','Which shipment had the highest delay?','Static','0'),
('LOGOV001','Multimode','Which projects have the highest actual transit time compared to budgeted transit time?','Static','0'),
('LOGOV001','Multimode','Create scatter chart on breakdown of transportation cost per unit based on the volume and delay?','Static','0'),
('LOGOV001','Multimode','Create a bar chart on  actual transportation costs vary by logistics service provider?','Static','0'),
('LOGOV001','Multimode','Which projects have the highest transportation costs for Roll On, Ocean Freight, and Roll Off? In tabluar format?','Static','0'),
('LOGOV001','Multimode','What is the total transportation cost with a breakdown for each project?','Static','0'),
('LOGOV001','Multimode','Which pickup location provides the least transit time for delivery to vizag?','Dynamic','0'),
('LOGOV001','Multimode','Give the details of the trip which got most delayed in  DFCU project?','Dynamic','0'),
('LOGOV001','Multimode','Which is corresponding LSP to project PFCCU which was maximum under budget?','Dynamic','0');

Insert into Suggestion_Queries (BotCode , SubCode , Question , Question_type , Question_frequency) values
('PPPW002','','Count of Open Punchpoints','Static','0'),
('PPPW002','','Can you provide the count of open punch points classified into P&ID and Non-P&ID categories?','Static','0'),
('PPPW002','','Which area has maximum OPEN punchpoints?','Static','0'),
('PPPW002','','Which action owner has maximum OPEN Punchpoints?','Static','0'),
('PPPW002','','Can you tell me OPEN punchpoints with respect to procurement?','Dynamic','0'),
('PPPW002','','Can you tell me OPEN punchpoints with respect to construction?','Dynamic','0'),
('PPPW002','','Can you tell me the system with least number of OPEN Punch-points?','Static','0'),
('PPPW002','','Count of open punchpoints in Area SS15','Dynamic','0'),
('PPPW002','','Count of open P&ID system punchpoints in Area SS15','Dynamic','0'),
('PPPW002','','Count of open non P&ID system punchpoints in Area SS15','Dynamic','0'),
('PPPW002','','Count of open E&P punchpoints in system no Area SS15','Dynamic','0'),
('PPPW002','','Count of open punchpoints in system no SS-15-ELS-23','Dynamic','0'),
('PPPW002','','Count of open P&ID punchpoints in system no SS-15-ELS-23','Dynamic','0'),
('PPPW002','','CCount of open non P&ID punchpoints in system no SS-15-ELS-23','Dynamic','0'),
('PPPW002','','Count of open E&P punchpoints in system no SS-15-ELS-23','Dynamic','0'),
('PPPW002','','Count of open punch points with EIL','Static','0'),
('PPPW002','','Count of open punch points with L&T','Static','0'),
('PPPW002','','Show the areawise barchart of the count of open punch points in descending order.','Static','0'),
('PPPW002','','Average time taken to close punchpoints','Static','0'),
('PPPW002','','Average time taken to close punchpoints by L&T','Static','0'),
('PPPW002','','Average time taken to close punchpoints by EIL','Static','0'),
('PPPW002','','Why EIL is taking so less time as PMC compared to L&T as EPC contractor?','Static','0'),
('PPPW002','','How can L&T reduce average closure time ?','Static','0'),
('PPPW002','','Can you suggest how much reduction is possible in L&Ts punchpoint closure time ?','Static','0'),
('PPPW002','','Can you explain end to end process of reporting and closure of punch points by L&T and EIL.','Static','0'),
('PPPW002','','can u explain me end to end punchpoint system in a very detailed manner','Static','0'),
('PPPW002','','Can you tell me ageing analysis of OPEN punchpoints waiting for L&T Closure?','Static','0'),
('PPPW002','','Can you tell me ageing analysis of OPEN punchpoints waiting for EIL acceptance?','Static','0'),
('PPPW002','','Can you tell me ageing analysis of OPEN punchpoints ?','Static','0'),
('PPPW002','','In last 6 months which area has closed the punchpoints in least time','Static','0'),
('PPPW002','','Average time taken by Kunal Saha the close the punch point','Dynamic','0'),
('PPPW002','','List of action owners for Area SRR9A and their average aging of open punchpoints','Dynamic','0'),
('PPPW002','','Display the trend of punch point closures over time, segmented by both L&T and EIL.','Static','0'),
('PPPW002','','How many critical punch points are open?','Static','0'),
('PPPW002','','Which subsystem has the most open critical punch points?','Static','0'),
('PPPW002','','What is the ageing analysis for open critical punch points?','Static','0'),
('PPPW002','','give me the count of subsystems whose format 3 acceptance is pending ?','Static','0'),
('PPPW002','','give me the count of systems whose format 2 acceptance is pending ?','Static','0'),
('PPPW002','','format 3 report status for subsystem no SS-15-ELS-01','Dynamic','0'),
('PPPW002','','Create a chart showing the number of systems completed for each individual format report','Static','0'),
('PPPW002','','Create a chart showing the number of sub-systems completed for each individual format report','Static','0'),
('PPPW002','','Create a grouped chart displaying the number of sub-systems submitted and accepted, categorized by each individual format report.','Static','0'),
('PPPW002','','Create a chart for system wise number of subsystems waiting for Final format closure','Static','0'),
('PPPW002','','Count of non P&ID subsystems whose format 3 acceptance is pending ?','Static','0'),
('PPPW002','','which area has highest no of format 3 closures ?','Static','0'),
('PPPW002','','Provide the subsystem-wise count of open punch points where the subsystem is awaiting Format 3 acceptance.','Static','0'),
('PPPW002','','Create a chart showcasing subsystem-wise count of open punch points where the subsystem is awaiting Format 3 acceptance.','Static','0'),
('PPPW002','','Create a chart showcasing system-wise count of open punch points where the subsystem is awaiting Format 3 acceptance.','Static','0'),
('PPPW002','','Create a chart showcasing area-wise count of open punch points where the subsystem is awaiting Format 3 acceptance.','Static','0'),
('PPPW002','','Identify the subsystems with the least number of open punch points and provide their corresponding format status report dates','Static','0'),
('PPPW002','','List down the details of subsystems have all punch points closed but are still waiting for Format 3 acceptance','Static','0'),
('PPPW002','','Design a mini dashboard to highlight key trends and visual insights from the data.','Static','0'),
('PPPW002','','Design a mini dashboard higlighting key insights about average time to close punchpoints','Static','0'),
('PPPW002','','Design a mini dashboard higlighting key insights about ageing analysis of open punchpoints','Static','0');



Insert into Suggestion_Queries (BotCode , SubCode , Question , Question_type , Question_frequency) values
('COMPW003','','Display the total count of punchpoints, classified into Open and Close','Static','0'),
('COMPW003','','Count of open punchpoints category wise.','Static','0'),
('COMPW003','','Create a pie chart for open punchpoints, category wise.','Static','0'),
('COMPW003','','Create a unit-wise chart showcasing the open punchpoint count in descending order.','Static','0'),
('COMPW003','','Which system has maximum open punchpoints.','Static','0'),
('COMPW003','','Which unit has least open punchpoints.','Static','0'),
('COMPW003','','Which discipline has the highest number of open punchpoints?.','Static','0'),
('COMPW003','','Which subsystem has maximum critical open punchpoints.','Static','0'),
('COMPW003','','In last 6 months which unit has closed the punchpoints in least time.','Static','0'),
('COMPW003','','Count of critical open punchpoints in unit number 504-101-P','Dynamic','0'),
('COMPW003','','Count of open punchpoints in subsystem number 504-SS-02A','Dynamic','0'),
('COMPW003','','Count of open punchpoints category wise in subsystem number 504-SS-02A','Dynamic','0'),
('COMPW003','','Display the count of critical open punchpoints.','Static','0'),
('COMPW003','','Display the count of exception open punchpoints.','Static','0'),
('COMPW003','','Create a chart showcasing the status-wise distribution of A category punchpoints.','Static','0'),
('COMPW003','','What is ageing analysis of open punchpoints ?','Static','0'),
('COMPW003','','Generate an excel for ageing analysis of critical open punchpoints.','Static','0'),
('COMPW003','','Average time taken to close punchpoints.','Static','0'),
('COMPW003','','Average time taken to close Critical punchpoints.','Static','0'),
('COMPW003','','How can L&T reduce average closure time ?','Static','0'),
('COMPW003','','Can you suggest how much reduction is possible in L&Ts punchpoint closure time ?','Static','0'),
('COMPW003','','can u explain me end to end about CENTENARY system in a very detailed manner?','Static','0'),
('COMPW003','','Create a chart displaying the average time taken to close punchpoints, categorized by punchpoint type?','Static','0'),
('COMPW003','','Display the trend of punch point closures over time','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart showing the total and closed critical punchpoints for each discipline, sorted by total punchpoint count in ascending order.','Static','0'),
('COMPW003','','Give me details & protocol status for tag number AI-905-01-024','Dynamic','0'),
('COMPW003','','How many protocols are open for subsystem number 504-SS-02A','Dynamic','0'),
('COMPW003','','How many construction protocols are open for subsystem number 504-SS-02A','Dynamic','0'),
('COMPW003','','How many pre-commissioning protocols are open for subsystem number 504-SS-02A','Dynamic','0'),
('COMPW003','','Display the total count of protocols, classified into Completed and Open','Static','0'),
('COMPW003','','Display the total count of open protocols, classified into Category A and Category B.','Static','0'),
('COMPW003','','Which subsystem has the highest number of pending protocols, and list down the tag details for the same subsystem?','Static','0'),
('COMPW003','','Which subsystem has more pending construction protocols ?','Static','0'),
('COMPW003','','Which subsystem has more pending precommissioning protocols ?','Static','0'),
('COMPW003','','Which unit has more pending construction protocols ?','Static','0'),
('COMPW003','','Display the trend of protocols closures over time.','Static','0'),
('COMPW003','','Create a donut chart displaying the distribution of Construction type protocols by status with the count values displayed on the chart.','Static','0'),
('COMPW003','','Create a donut chart displaying the distribution of Precommissioning type protocols by status with the count values displayed on the chart.','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart displaying the total number of Construction-type protocols and the number completed for each discipline, sorted in ascending order by total protocol count.','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart displaying the total number of Precommissioning-type protocols and the number completed for each discipline, sorted in ascending order by total protocol count.','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart displaying the total number of Construction-type protocols and the number completed for each system-type, sorted in ascending order by total protocol count.','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart displaying the total number of Precommissioning-type protocols and the number completed for each system-type, sorted in ascending order by total protocol count.','Static','0'),
('COMPW003','','Display the total number of closed Format 1 certificates.','Static','0'),
('COMPW003','','Display the total number of closed certificates for each format type','Static','0'),
('COMPW003','','Give me the individual format report wise details for subsystem number 504-SS-02A','Dynamic','0'),
('COMPW003','','Give me the format 3 report details for subsystem number 504-SS-02A','Dynamic','0'),
('COMPW003','','Give me the count of subsystems whose format 3 acceptance is pending ?','Static','0'),
('COMPW003','','Which system has the highest number of open Format 3 certificates, and what is the count?','Static','0'),
('COMPW003','','Which unit has the highest number of closed Format 3 certificates, and what is the count?','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart showing the total and closed Format 1 reports for each system type, sorted by total report count in ascending order.','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart showing the total and closed Format 2 reports for each system type, sorted by total report count in ascending order.','Static','0'),
('COMPW003','','Create a horizontal clustered bar chart showing the total and closed Format 3 reports for each system type, sorted by total report count in ascending order.','Static','0'),
('COMPW003','','Create a chart showing the number of subsystems with closed Format 3 certificates for each system.','Static','0'),
('COMPW003','','Display the monthly trend of individual format certificate closures over time.','Static','0'),
('COMPW003','','Display the monthly trend of  format 3 certificate closures over time.','Static','0'),
('COMPW003','','Which subsystem has the highest number of open punchpoints and its indiviudal format report status','Static','0'),
('COMPW003','','Provide the subsystem-wise count of open punch points where the subsystem is awaiting Format 3 acceptance.','Static','0'),
('COMPW003','','Create a chart showcasing subsystem-wise count of open punch points where the subsystem is awaiting Format 3 acceptance.','Static','0'),
('COMPW003','','Identify the subsystem with the least number of open punch points and provide their corresponding format status report dates','Static','0'),
('COMPW003','','Track the progress of format certificate closures for subsystems with open punchpoints.','Static','0'),
('COMPW003','','Compare the punchpoint closure rates and protocol completion rates across different units.','Static','0'),
('COMPW003','','Identify the subsystem with the highest number of open punchpoints. List all format certificate statuses for this subsystem, and also provide the protocol status and tags details for the same subsystem.','Static','0'),
('COMPW003','','Provide the Punch Point, Format Report Status, and Protocol Information for Subsystem 504-SS-02A','Dynamic','0'),
('COMPW003','','Design a mini dashboard to highlight key trends and visual insights from the data.','Static','0'),
('COMPW003','','Design a mini dashboard higlighting key insights about average time to close punchpoints','Static','0'),
('COMPW003','','Design a mini dashboard higlighting key insights about format certificates data','Static','0'),
('COMPW003','','Design a mini dashboard higlighting key insights about protocols data','Static','0');














